
# What is PyTorch?

It’s a Python-based scientific computing package targeted at two sets of
audiences:

 *  A replacement for NumPy to use the power of GPUs
 *  a deep learning research platform that provides maximum flexibility and speed


In [1]:
import torch

## Tensors

* Tensors are similar to NumPy’s ndarrays, with the addition being that
* Tensors can also be used on a GPU to accelerate computing.

**_Note:_** An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.



Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.2612e-44,  0.0000e+00, -1.4417e-35],
        [ 4.5773e-41, -1.1674e-14,  3.0660e-41],
        [        nan,         nan,  0.0000e+00],
        [ 0.0000e+00,         nan,         nan],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2753, 0.5642, 0.0486],
        [0.8075, 0.6482, 0.3002],
        [0.3635, 0.2036, 0.9833],
        [0.1823, 0.5091, 0.0073],
        [0.9670, 0.6349, 0.6913]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9934,  0.3487,  0.3726],
        [ 0.1265, -0.3800, -1.1921],
        [ 2.1535, -0.9244, -0.0055],
        [-2.1453, -1.2738, -0.2230],
        [ 0.3765, -1.3691,  1.9273]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


**_Note:_** `torch.size` is in fact a tuple, so it supports all tuple operations.


## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.4461,  1.2642,  1.1159],
        [ 1.0441,  0.4131, -0.7888],
        [ 2.1589, -0.0176,  0.0756],
        [-1.6454, -0.5655, -0.1729],
        [ 0.8892, -0.8552,  2.5645]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[-0.4461,  1.2642,  1.1159],
        [ 1.0441,  0.4131, -0.7888],
        [ 2.1589, -0.0176,  0.0756],
        [-1.6454, -0.5655, -0.1729],
        [ 0.8892, -0.8552,  2.5645]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4461,  1.2642,  1.1159],
        [ 1.0441,  0.4131, -0.7888],
        [ 2.1589, -0.0176,  0.0756],
        [-1.6454, -0.5655, -0.1729],
        [ 0.8892, -0.8552,  2.5645]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.4461,  1.2642,  1.1159],
        [ 1.0441,  0.4131, -0.7888],
        [ 2.1589, -0.0176,  0.0756],
        [-1.6454, -0.5655, -0.1729],
        [ 0.8892, -0.8552,  2.5645]])


**_Note:_** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)` or `x.t_()`, will change `x`

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([ 0.3487, -0.3800, -0.9244, -1.2738, -1.3691])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9274])
-0.9273894429206848


**Read later:**

  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described in `<https://pytorch.org/docs/torch>`

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the `.to` method.



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.0726], device='cuda:0')
tensor([0.0726], dtype=torch.float64)
